Story1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugas.urls'))
]

tugas/urls.py
from django.urls import path
from . import views
app_name = 'main'
urlpatterns = [
    path('',views.home,name='index'),
    path('home', views.story4home, name='story4home'),
    path('lainnya', views.story4lainnya, name='story4lainnya'),
]

tugas/models.py
from django.db import models

# Create your models here.

tugas/forms.py
from django import forms

##Create your forms here

tugas/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect

# Create your views here.
def home(request):
    return render(request,'pages/index.html',{})
def story4home(request):
    url = 'https://story-jafarabdurrohman.herokuapp.com/'
    return HttpResponseRedirect(url)
def story4lainnya(request):
    url = 'https://story-jafarabdurrohman.herokuapp.com/lain'
    return HttpResponseRedirect(url)

tugas/templates/pages/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profil saya</title>
</head>
<body>
    {% include 'pages/navbar.html' %}
<div>
    <img src="{% static 'assets/16393.jpg' %}" width='150' height='200'>
</div>
<div >
    <h2>Biodata</h2>
    <table>
        <tr>
            <td>Nama</td>
            <td>Jafar Abdurrohman</td>
        </tr>

        <tr>
            <td>NPM</td>
            <td>1906350843</td>
        </tr>

        <tr>
            <td>Angkatan</td>
            <td>2019</td>
        </tr>

        <tr>
            <td>Hobi</td>
            <td>Membaca</td>
        </tr>

        <tr>
            <td>Kuliah</td>
            <td>Fasilkom UI</td>
        </tr>
    </table>
</div>

<div>
    <h2>Deskripsi tentang saya</h2>
    <p>Anak ke 3 di keluarga dengan 5 orang anak. sejak kecil suka berolahraga dan menaruh minat di bidang IT.</p>
</div>

<div>
    <h2>Riwayat Pendidikan</h2>
    <table>
        <tr>
            <td>2005-2007</td>
            <td>TK Bahrul ulum</td>
        </tr>

        <tr>
            <td>2007-2013</td>
            <td>SD Negeri Puspiptek</td>
        </tr>

        <tr>
            <td>2013-2016</td>
            <td>SMPIT Insan Harapan</td>
        </tr>

        <tr>
            <td>2016-2019</td>
            <td>SMA Negeri 2 Tangerang Selatan</td>
        </tr>

        <tr>
            <td>2019-Sekarang</td>
            <td>Universitas Indonesia</td>
        </tr>
    </table>
    <div>
        <h2>Media Sosial</h2>
        <table>
            <tr>
                <td>Twitter</td>
                <td>jafar</td>
            </tr>

            <tr>
                <td>Instagram</td>
                <td>jafar</td>
            </tr>
        </table>

</div>
</body>
</html>

tugas/templates/pages/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<nav>
    <div class="logo">
        <h3>Jafar Abdurrohman</h3>
    </div>
    <ul>
        <li><a href="{% url 'main:story4home' %}">Home</a></li>
        <li><a href="{% url 'main:story4lainnya' %}">Lainnya</a></li>
        <li><a href="{% url 'main:index' %}">Story1</a></li>
    </ul>
</nav>
</body>
</html>